#!/usr/bin/env python3
"""Copy the sample paper from web/src/lib/sample.ts into Swift, byte for byte.

Run from anywhere:  python3 mobile/ios/scripts/gen_sample.py
A unit test (SampleTests) re-reads sample.ts and fails if the two ever drift.
"""
import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
src = open(os.path.join(ROOT, "web", "src", "lib", "sample.ts"), encoding="utf-8").read()
text = re.search(r"SAMPLE_AVS = `(.*?)`;", src, re.S).group(1)
label = re.search(r'SAMPLE_LABEL = "(.*?)";', src).group(1)
assert '"""' not in text and "\\" not in text

out = f'''// GENERATED by mobile/ios/scripts/gen_sample.py from web/src/lib/sample.ts. Do not edit by hand.
// SAMPLE DOCUMENT written by Team ATLAS. It describes no real patient and contains no real health information.

enum Sample {{
    static let label = "{label}"

    static let text = """
{text}
"""
}}
'''
dest = os.path.join(ROOT, "mobile", "ios", "ATLAS", "Support", "Sample.swift")
os.makedirs(os.path.dirname(dest), exist_ok=True)
open(dest, "w", encoding="utf-8").write(out)
print("wrote", dest, len(text), "chars")
