#!/usr/bin/env python3
"""Writes the phone apps' copy of the safety patterns from mobile/shared/safety-vectors.json.

The website's rules (web/src/lib/warningPin.ts, web/src/lib/stepsView.ts) are the source. The generator test
(genSafetyVectors.test.ts) puts the exact source and flags of every pattern they use in safety-vectors.json, and this
script copies that table into:

  mobile/ios/ATLAS/Support/SafetyPatterns.swift
  mobile/android/app/src/main/java/com/stephensookra/atlas/data/SafetyPatterns.kt

so all three apps run the same pattern text. Both apps' tests compare their table with safety-vectors.json and fail on
any difference, so a pattern changed on the web and not copied here turns the phone CI red.

Run after regenerating safety-vectors.json:  python3 mobile/shared/gen-native-patterns.py
"""
import json
import pathlib

root = pathlib.Path(__file__).resolve().parents[2]
patterns = json.loads((root / "mobile/shared/safety-vectors.json").read_text(encoding="utf-8"))["patterns"]

for name, p in patterns.items():
    src = p["source"]
    # Raw-string safety: Swift #"..."# and Kotlin """...""" (where $ would start a template).
    # \s and \d are rewritten when compiled, so neither may appear escaped (\\s) or inside a character class.
    assert "\\\\" not in src, f"{name} has an escaped backslash"
    depth, i = 0, 0
    while i < len(src):
        c = src[i]
        if c == "\\":
            assert not (depth and src[i + 1] in "sd"), f"{name} uses \\{src[i + 1]} inside a character class"
            i += 2
            continue
        depth += c == "["
        depth -= c == "]" and depth > 0
        i += 1
    assert '"#' not in src and '"""' not in src and "$" not in src, f"{name} cannot be written as a raw string"
    assert name.isidentifier(), name

HEADER = "Generated by mobile/shared/gen-native-patterns.py from mobile/shared/safety-vectors.json. Do not edit by hand."
# JavaScript's \s, spelled out (web/src/lib/verify.ts and MissedLines use the same class).
JS_SPACE = "[\\t\\n\\u000B\\f\\r \\u00A0\\u1680\\u2000-\\u200A\\u2028\\u2029\\u202F\\u205F\\u3000\\uFEFF]"

swift = [f"// {HEADER}", "import Foundation", "",
         "/// One pattern from the website's safety rules: its exact source and JavaScript flags.",
         "struct SafetyPattern: Sendable, Equatable {", "    let source: String", "    let flags: String", "",
         "    /// JavaScript's \\s, spelled out, so a pattern matches the same spaces as on the website.",
         f'    static let jsSpaceClass = #"{JS_SPACE}"#', "",
         "    /// Compiled with the website's meaning: \"i\" is case-insensitive (Unicode), \\s is JavaScript's \\s and \\d is",
         "    /// 0-9 only (ICU's \\d would also take other scripts' digits, which JavaScript's does not).",
         "    func regex() -> NSRegularExpression {",
         '        let src = source.replacingOccurrences(of: #"\\s"#, with: Self.jsSpaceClass).replacingOccurrences(of: #"\\d"#, with: "[0-9]")',
         '        return try! NSRegularExpression(pattern: src, options: flags.contains("i") ? [.caseInsensitive] : [])',
         "    }", "}", "",
         "/// The patterns of web/src/lib/warningPin.ts and web/src/lib/stepsView.ts, word for word.",
         "enum SafetyPatterns {"]
for name, p in patterns.items():
    swift.append(f'    static let {name} = SafetyPattern(source: #"{p["source"]}"#, flags: "{p["flags"]}")')
swift += ["", "    static let all: [String: SafetyPattern] = ["]
swift += [f'        "{name}": {name},' for name in patterns]
swift += ["    ]", "}", ""]
(root / "mobile/ios/ATLAS/Support/SafetyPatterns.swift").write_text("\n".join(swift), encoding="utf-8")

kotlin = [f"// {HEADER}", "package com.stephensookra.atlas.data", "", "import java.util.regex.Pattern", "",
          "/** One pattern from the website's safety rules: its exact source and JavaScript flags. */",
          "data class SafetyPattern(val source: String, val flags: String) {",
          "    /** Compiled with the website's meaning: \"i\" is case-insensitive (Unicode), \\s is JavaScript's \\s, \\d is 0-9. */",
          "    fun regex(): Regex = Pattern.compile(",
          '        source.replace("""\\s""", JS_SPACE_CLASS).replace("""\\d""", "[0-9]"),',
          "        if ('i' in flags) Pattern.CASE_INSENSITIVE or Pattern.UNICODE_CASE else 0,",
          "    ).toRegex()", "",
          "    companion object {",
          "        /** JavaScript's \\s, spelled out (Java's \\s is ASCII only). */",
          f'        const val JS_SPACE_CLASS = """{JS_SPACE}"""',
          "    }", "}", "",
          "/** The patterns of web/src/lib/warningPin.ts and web/src/lib/stepsView.ts, word for word. */",
          "@Suppress(\"ObjectPropertyName\", \"PropertyName\")",
          "object SafetyPatterns {"]
for name, p in patterns.items():
    kotlin.append(f'    val {name} = SafetyPattern("""{p["source"]}""", "{p["flags"]}")')
kotlin += ["", "    val all: Map<String, SafetyPattern> = mapOf("]
kotlin += [f'        "{name}" to {name},' for name in patterns]
kotlin += ["    )", "}", ""]
(root / "mobile/android/app/src/main/java/com/stephensookra/atlas/data/SafetyPatterns.kt").write_text("\n".join(kotlin), encoding="utf-8")
print(f"wrote {len(patterns)} patterns for iOS and Android")
