// Generated by mobile/shared/gen-native-patterns.py from mobile/shared/safety-vectors.json. Do not edit by hand.
import Foundation

/// One pattern from the website's safety rules: its exact source and JavaScript flags.
struct SafetyPattern: Sendable, Equatable {
    let source: String
    let flags: String

    /// JavaScript's \s, spelled out, so a pattern matches the same spaces as on the website.
    static let jsSpaceClass = #"[\t\n\u000B\f\r \u00A0\u1680\u2000-\u200A\u2028\u2029\u202F\u205F\u3000\uFEFF]"#

    /// Compiled with the website's meaning: "i" is case-insensitive (Unicode), \s is JavaScript's \s.
    func regex() -> NSRegularExpression {
        let src = source.replacingOccurrences(of: #"\s"#, with: Self.jsSpaceClass)
        return try! NSRegularExpression(pattern: src, options: flags.contains("i") ? [.caseInsensitive] : [])
    }
}

/// The patterns of web/src/lib/warningPin.ts and web/src/lib/stepsView.ts, word for word.
enum SafetyPatterns {
    static let WARNING_WORDS = SafetyPattern(source: #"(?<![\p{L}\p{N}])(?:911|emergency\s+(?:room|department|services|care)|emergencies|emergency|urgent\s+care|go\s+to\s+the\s+(?:nearest\s+)?hospital|seek\s+(?:\p{L}+\s+)?(?:care|help|attention|treatment)|get\s+(?:medical\s+)?help\s+(?:right\s+away|now|immediately)|call\s+(?:(?:the|your|our)\s+)?(?:\p{L}+['’]s\s+)?(?:office|clinic|doctor|physician|provider|nurse|care\s+team)\s+(?:right\s+away|immediately|at\s+once|now)|chest\s+(?:pain|pressure|tightness)|(?:trouble|difficulty|hard)\s+breathing|short(?:ness)?\s+of\s+breath|can(?:no|['’])t\s+breathe|cannot\s+breathe|faint(?:ing|ed)|feel(?:s|ing)?\s+faint|pass(?:ing)?\s+out|seizures?|stroke|sudden\s+(?:weakness|numbness|confusion)|severe\s+(?:bleeding|pain|headache|allergic)|suicid\p{L}*|llame\s+al\s+911|sala\s+de\s+emergencias?|emergencias?|urgencias|vaya\s+al\s+hospital|busque\s+(?:atenci[oó]n|ayuda)|dolor\s+(?:de|en\s+el)\s+pecho|dificultad\s+para\s+respirar|falta\s+de\s+aire|desmay\p{L}*|convulsi\p{L}*)(?![\p{L}\p{N}])"#, flags: "iu")
    static let NOT_EMERGENCY = SafetyPattern(source: #"(?<![\p{L}\p{N}])(?:not\s+(?:an\s+|a\s+)?|non-?|no\s+es\s+(?:una\s+)?)(?:emergency|emergencia|urgent)(?![\p{L}\p{N}])"#, flags: "giu")
    static let ER = SafetyPattern(source: #"(?<![\p{L}\p{N}])(?:ER)(?![\p{L}\p{N}])"#, flags: "u")

    static let all: [String: SafetyPattern] = [
        "WARNING_WORDS": WARNING_WORDS,
        "NOT_EMERGENCY": NOT_EMERGENCY,
        "ER": ER,
    ]
}
