// Generated by mobile/shared/gen-native-patterns.py from mobile/shared/safety-vectors.json. Do not edit by hand.
package com.stephensookra.atlas.data

import java.util.regex.Pattern

/** One pattern from the website's safety rules: its exact source and JavaScript flags. */
data class SafetyPattern(val source: String, val flags: String) {
    /** Compiled with the website's meaning: "i" is case-insensitive (Unicode), \s is JavaScript's \s, \d is 0-9. */
    fun regex(): Regex = Pattern.compile(
        source.replace("""\s""", JS_SPACE_CLASS).replace("""\d""", "[0-9]"),
        if ('i' in flags) Pattern.CASE_INSENSITIVE or Pattern.UNICODE_CASE else 0,
    ).toRegex()

    companion object {
        /** JavaScript's \s, spelled out (Java's \s is ASCII only). */
        const val JS_SPACE_CLASS = """[\t\n\u000B\f\r \u00A0\u1680\u2000-\u200A\u2028\u2029\u202F\u205F\u3000\uFEFF]"""
    }
}

/** The patterns of web/src/lib/warningPin.ts and web/src/lib/stepsView.ts, word for word. */
@Suppress("ObjectPropertyName", "PropertyName")
object SafetyPatterns {
    val WARNING_WORDS = SafetyPattern("""(?<![\p{L}\p{N}])(?:911|emergency\s+(?:room|department|services|care)|emergencies|emergency|urgent\s+care|go\s+to\s+the\s+(?:nearest\s+)?hospital|seek\s+(?:\p{L}+\s+)?(?:care|help|attention|treatment)|get\s+(?:medical\s+)?help\s+(?:right\s+away|now|immediately)|call\s+(?:(?:the|your|our)\s+)?(?:\p{L}+['’]s\s+)?(?:office|clinic|doctor|physician|provider|nurse|care\s+team)\s+(?:right\s+away|immediately|at\s+once|now)|chest\s+(?:pain|pressure|tightness)|(?:trouble|difficulty|hard)\s+breathing|short(?:ness)?\s+of\s+breath|can(?:no|['’])t\s+breathe|cannot\s+breathe|faint(?:ing|ed)|feel(?:s|ing)?\s+faint|pass(?:ing)?\s+out|seizures?|stroke|sudden\s+(?:weakness|numbness|confusion)|severe\s+(?:bleeding|pain|headache|allergic)|suicid\p{L}*|llame\s+al\s+911|sala\s+de\s+emergencias?|emergencias?|urgencias|vaya\s+al\s+hospital|busque\s+(?:atenci[oó]n|ayuda)|dolor\s+(?:de|en\s+el)\s+pecho|dificultad\s+para\s+respirar|falta\s+de\s+aire|desmay\p{L}*|convulsi\p{L}*)(?![\p{L}\p{N}])""", "iu")
    val NOT_EMERGENCY = SafetyPattern("""(?<![\p{L}\p{N}])(?:not\s+(?:an\s+|a\s+)?|non-?|no\s+es\s+(?:una\s+)?)(?:emergency|emergencia|urgent)(?![\p{L}\p{N}])""", "giu")
    val ER = SafetyPattern("""(?<![\p{L}\p{N}])(?:ER)(?![\p{L}\p{N}])""", "u")
    val WHEN_RULE_0 = SafetyPattern("""(?<![\p{L}\p{N}])(?:today|tonight|right\s+now|now|right\s+away|immediately|this\s+(?:morning|afternoon|evening))(?![\p{L}\p{N}])""", "giu")
    val WHEN_RULE_1 = SafetyPattern("""(?<![\p{L}\p{N}])(?:hoy|ahora\s+mismo|ahora|de\s+inmediato|inmediatamente|enseguida|esta\s+(?:noche|tarde|ma[nñ]ana))(?![\p{L}\p{N}])""", "giu")
    val WHEN_RULE_2 = SafetyPattern("""(?<![\p{L}\p{N}])(?:(?:within|in|after|in\s+the\s+next|over\s+the\s+next|during\s+the\s+next|due\s+in|dentro\s+de|en|en\s+l[oa]s\s+pr[oó]xim[oa]s|despu[eé]s\s+de)\s+(\d{1,3}|fourteen|fifteen|catorce|treinta|eleven|twelve|twenty|thirty|cuatro|quince|veinte|three|seven|eight|cinco|siete|nueve|four|five|nine|tres|seis|ocho|diez|once|doce|one|two|six|ten|una|uno|dos|an|un|a)\s+(days?|d[ií]as?|weeks?|semanas?))(?![\p{L}\p{N}])""", "giu")
    val WHEN_RULE_3 = SafetyPattern("""(?<![\p{L}\p{N}])(?:tomorrow|this\s+week|next\s+week|in\s+a\s+few\s+days|within\s+a\s+few\s+days)(?![\p{L}\p{N}])""", "giu")
    val WHEN_RULE_4 = SafetyPattern("""(?<![\p{L}\p{N}])(?:esta\s+semana|la\s+pr[oó]xima\s+semana|la\s+semana\s+que\s+viene|en\s+unos\s+d[ií]as)(?![\p{L}\p{N}])""", "giu")
    val WHEN_RULE_5 = SafetyPattern("""(?<![\p{L}\p{N}])(?:(?:within|in|after|in\s+the\s+next|over\s+the\s+next|during\s+the\s+next|due\s+in|dentro\s+de|en|en\s+l[oa]s\s+pr[oó]xim[oa]s|despu[eé]s\s+de)\s+(\d{1,3}|fourteen|fifteen|catorce|treinta|eleven|twelve|twenty|thirty|cuatro|quince|veinte|three|seven|eight|cinco|siete|nueve|four|five|nine|tres|seis|ocho|diez|once|doce|one|two|six|ten|una|uno|dos|an|un|a)\s+(months?|mes|meses|years?|a[nñ]os?))(?![\p{L}\p{N}])""", "giu")
    val WHEN_RULE_6 = SafetyPattern("""(?<![\p{L}\p{N}])(?:next\s+(?:month|year)|every\s+(\d{1,3}|fourteen|fifteen|catorce|treinta|eleven|twelve|twenty|thirty|cuatro|quince|veinte|three|seven|eight|cinco|siete|nueve|four|five|nine|tres|seis|ocho|diez|once|doce|one|two|six|ten|una|uno|dos|an|un|a)\s+(?:months|years)|el\s+pr[oó]ximo\s+(?:mes|a[nñ]o)|el\s+(?:mes|a[nñ]o)\s+que\s+viene|cada\s+(\d{1,3}|fourteen|fifteen|catorce|treinta|eleven|twelve|twenty|thirty|cuatro|quince|veinte|three|seven|eight|cinco|siete|nueve|four|five|nine|tres|seis|ocho|diez|once|doce|one|two|six|ten|una|uno|dos|an|un|a)\s+(?:meses|a[nñ]os))(?![\p{L}\p{N}])""", "giu")
    val WHEN_RULE_7 = SafetyPattern("""(?<![\p{L}\p{N}])(?:daily|nightly|weekly|every\s+(?:day|morning|night|evening|afternoon|week)|each\s+(?:day|morning|night|evening|week)|at\s+bedtime|once\s+a\s+(?:day|week)|twice\s+a\s+(?:day|week)|(\d{1,3}|fourteen|fifteen|catorce|treinta|eleven|twelve|twenty|thirty|cuatro|quince|veinte|three|seven|eight|cinco|siete|nueve|four|five|nine|tres|seis|ocho|diez|once|doce|one|two|six|ten|una|uno|dos|an|un|a)\s+times?\s+(?:a|per|each)\s+(?:day|week)|(\d{1,3}|fourteen|fifteen|catorce|treinta|eleven|twelve|twenty|thirty|cuatro|quince|veinte|three|seven|eight|cinco|siete|nueve|four|five|nine|tres|seis|ocho|diez|once|doce|one|two|six|ten|una|uno|dos|an|un|a)\s+times\s+daily|(\d{1,3}|fourteen|fifteen|catorce|treinta|eleven|twelve|twenty|thirty|cuatro|quince|veinte|three|seven|eight|cinco|siete|nueve|four|five|nine|tres|seis|ocho|diez|once|doce|one|two|six|ten|una|uno|dos|an|un|a)\s+days?\s+(?:a|per|each)\s+week|every\s+(\d{1,3}|fourteen|fifteen|catorce|treinta|eleven|twelve|twenty|thirty|cuatro|quince|veinte|three|seven|eight|cinco|siete|nueve|four|five|nine|tres|seis|ocho|diez|once|doce|one|two|six|ten|una|uno|dos|an|un|a)\s+(?:hours|days|weeks)|(?:a|per)\s+day)(?![\p{L}\p{N}])""", "giu")
    val WHEN_RULE_8 = SafetyPattern("""(?<![\p{L}\p{N}])(?:diario|diaria|diariamente|semanalmente|cada\s+(?:d[ií]a|ma[nñ]ana|noche|tarde|semana)|todos\s+los\s+d[ií]as|todas\s+las\s+(?:ma[nñ]anas|noches|tardes)|al\s+acostarse|una\s+vez\s+al\s+d[ií]a|dos\s+veces\s+al\s+d[ií]a|(\d{1,3}|fourteen|fifteen|catorce|treinta|eleven|twelve|twenty|thirty|cuatro|quince|veinte|three|seven|eight|cinco|siete|nueve|four|five|nine|tres|seis|ocho|diez|once|doce|one|two|six|ten|una|uno|dos|an|un|a)\s+veces\s+(?:al|por)\s+(?:d[ií]a|semana)|(\d{1,3}|fourteen|fifteen|catorce|treinta|eleven|twelve|twenty|thirty|cuatro|quince|veinte|three|seven|eight|cinco|siete|nueve|four|five|nine|tres|seis|ocho|diez|once|doce|one|two|six|ten|una|uno|dos|an|un|a)\s+d[ií]as\s+(?:a|por)\s+(?:la\s+)?semana|cada\s+(\d{1,3}|fourteen|fifteen|catorce|treinta|eleven|twelve|twenty|thirty|cuatro|quince|veinte|three|seven|eight|cinco|siete|nueve|four|five|nine|tres|seis|ocho|diez|once|doce|one|two|six|ten|una|uno|dos|an|un|a)\s+(?:horas|d[ií]as|semanas)|(?:al|por)\s+d[ií]a)(?![\p{L}\p{N}])""", "giu")
    val OTHER_LATIN = SafetyPattern("""[ãõçâêôàèùûëïœ]""", "iu")
    val NEGATION = SafetyPattern("""(?<![\p{L}])(?:not|\p{L}+n['’]t|never|no|nunca|ni|tampoco)(?![\p{L}])""", "iu")
    val STOP = SafetyPattern("""(?<![\p{L}\p{N}])(?:stop|stopped|discontinue|discontinued|do\s+not\s+take|don['’]t\s+take|never\s+take|deje\s+de\s+tomar|dejar\s+de\s+tomar|suspenda|suspender|no\s+tome|no\s+tomar)(?![\p{L}\p{N}])""", "giu")
    val NOT_NOW = SafetyPattern("""(?<![\p{L}\p{N}])(?:(?:do\s+not|don['’]t|never|not)(?:\s+\p{L}+){0,2}\s+(?:stop|discontinue)|no(?:\s+\p{L}+){0,2}\s+(?:deje|dejar|suspenda|suspender)|if|unless|when|before|after|si|cuando|antes\s+de|despu[eé]s\s+de|more\s+than|m[aá]s\s+de|exceed|with(?!\s+(?:no\s+)?delay)|without(?!\s+delay)|empty\s+stomach|same\s+time|together|con|sin(?!\s+demora)|en\s+ayunas)(?![\p{L}\p{N}])""", "giu")
    val BULLET = SafetyPattern("""^\s*(?:[-*•‣–]|\d{1,2}[.)])\s+""", "u")
    val WARNING_MORE = SafetyPattern("""(?<![\p{N}A-Za-z\u00C0-\u024F])(?:911|9-1-1)(?![\p{N}A-Za-z\u00C0-\u024F])|(?<![\p{L}\p{N}])(?:gọi\s+(?:ngay\s+)?(?:cho\s+)?cấp\s+cứu|cấp\s+cứu|khẩn\s+cấp|đau\s+ngực|tức\s+ngực|khó\s+thở|thở\s+gấp|ngất\s+xỉu|ngất|bất\s+tỉnh|co\s+giật|đột\s+quỵ|chảy\s+máu\s+(?:nhiều|không\s+cầm)|(?:đến|đi)\s+bệnh\s+viện\s+ngay|gọi\s+(?:cho\s+)?(?:bác\s+sĩ|phòng\s+khám)(?:\s+\p{L}+)?\s+ngay)(?![\p{L}\p{N}])|(?<![\p{L}\p{N}])(?:urgences?|appele[rz]\s+les\s+secours|douleurs?\s+(?:thoraciques?|(?:à|dans)\s+la\s+poitrine)|oppression\s+thoracique|difficultés?\s+(?:à\s+respirer|respiratoires?)|du\s+mal\s+à\s+respirer|essoufflements?|souffle\s+court|évanoui\p{L}*|perte\s+de\s+connaissance|perde[zr]\s+connaissance|convulsions?|crises?\s+d['’]épilepsie|AVC|accident\s+vasculaire\s+cérébral|consulte[rz]\s+(?:un\s+médecin\s+)?(?:immédiatement|d['’]urgence|sans\s+tarder)|(?:rende[zr]-vous|alle[rz])\s+(?:aux\s+urgences|à\s+l['’]hôpital)|appele[rz]\s+(?:votre\s+|le\s+)?(?:médecin|cabinet|clinique)\s+(?:immédiatement|tout\s+de\s+suite)|saignements?\s+(?:abondants?|importants?|graves?))(?![\p{L}\p{N}])|응급|구급차|흉통|가슴\s*통증|가슴\s*조임|가슴이\s*(?:아프|조이|답답)|호흡\s*곤란|숨이\s*(?:차|가쁘)|숨\s*가쁨|숨쉬기\s*(?:가\s*)?(?:어렵|힘들)|기절|실신|의식을\s*잃|발작|경련|뇌졸중|즉시\s*(?:병원|의사|의료진|진료)|急诊|急診|急救|紧急|緊急|胸痛|胸口痛|胸部疼痛|胸闷|胸悶|呼吸困难|呼吸困難|呼吸急促|呼吸短促|气短|氣短|喘不过气|喘不過氣|晕倒|暈倒|晕厥|暈厥|昏厥|昏倒|失去知觉|失去知覺|意识丧失|意識喪失|抽搐|癫痫发作|癲癇發作|中风|中風|立即就医|立即就醫|马上就医|馬上就醫|立即寻求医疗|立即尋求醫療|立即致电|立即致電|严重出血|嚴重出血|大量出血|出血不止|无法止血|無法止血|ድንገተኛ|የደረት\s*(?:ህመም|ሕመም)|የመተንፈስ\s*ችግር|(?:የ)?ትንፋሽ\s*(?:እጥረት|ማጠር)|ራስን\s*መሳት|መናድ|ስትሮክ|ወዲያውኑ\s*(?:ወደ\s*)?(?:[ሐሀሃ]ኪም|ሆስፒታል)|ወደ\s*ሆስፒታል\s*ይሂዱ""", "iu")
    val NOT_EMERGENCY_MORE = SafetyPattern("""(?<![\p{L}\p{N}])(?:không\s+phải(?:\s+\p{L}+){0,3}\s+(?:cấp\s+cứu|khẩn\s+cấp))(?![\p{L}\p{N}])|(?<![\p{L}\p{N}])(?:pas\s+(?:une\s+|d['’]\s*)?urgen\p{L}*|non(?:-|\s+)urgen\p{L}*|hors\s+urgence)(?![\p{L}\p{N}])|비\s*응급|응급(?:\s*상황)?(?:이|은|는|가)?\s*아(?:닙|닌|니)|(?:不是|并非|並非|非)\s*(?:一个|一個)?\s*(?:紧急|緊急|急诊|急診)|不紧急|不緊急|ድንገተኛ(?:\s+\p{L}+)?\s+አይደለም|ድንገተኛ\s+ያልሆነ""", "giu")
    val STOP_VI = SafetyPattern("""(?<![\p{L}\p{N}])(?:ngưng|ngừng|dừng|(?:không|đừng)\s+(?:được\s+)?(?:dùng|uống))(?![\p{L}\p{N}])""", "iu")
    val NOT_NOW_VI = SafetyPattern("""(?<![\p{L}\p{N}])(?:(?:không|đừng|chớ)(?:\s+\p{L}+){0,3}\s+(?:ngưng|ngừng|dừng)|nếu|trừ\s+khi|khi|trường\s+hợp|trước|sau\s+(?:khi|\d|một|hai|ba|bốn|năm|vài)|quá|nhiều\s+hơn|tối\s+đa|vượt|với|cùng\s+lúc|lúc\s+đói|bụng\s+đói|rượu)(?![\p{L}\p{N}])""", "iu")
    val STOP_FR = SafetyPattern("""(?<![\p{L}\p{N}])(?:arrêt(?:ez|er)|arret(?:ez|er)|cess(?:ez|er)|interromp(?:ez|re)|suspend(?:ez|re)|ne\s+(?:prenez|pas\s+prendre|plus\s+prendre)|n['’]utilisez\s+(?:pas|plus))(?![\p{L}\p{N}])""", "iu")
    val NOT_NOW_FR = SafetyPattern("""(?<![\p{L}\p{N}])(?:n['’]\s*(?:arrêtez|arretez|interrompez|cessez|suspendez)|ne\s+(?:\p{L}+\s+){0,2}(?:arrêt|arret|cess|interromp|suspend)\p{L}*|si|s['’]ils?|sauf|lorsque|lorsqu['’]\p{L}+|quand|en\s+cas|avant|après|dès\s+que|plus\s+de|dépasse[rz]|au-delà|maximum|avec|sans(?!\s+(?:délai|tarder|attendre))|à\s+jeun|estomac\s+vide|en\s+même\s+temps|ensemble|alcool)(?![\p{L}\p{N}])""", "iu")
    val STOP_KO = SafetyPattern("""중단|중지|끊으|끊고|끊어|복용하지\s*마|드시지\s*마|먹지\s*마|사용하지\s*마|복용\s*금지""", "iu")
    val NOT_NOW_KO = SafetyPattern("""(?:중단|중지|끊)\p{L}*?지\s*(?:마|말|않)|경우|만약|만일|(?:하|으|이|되|나|생기|나타나|있으|없으|않으)면(?![\p{L}])|때(?!문)|전에|이전|후에|이후|일\s*후|주\s*후|수술\s*전|이상|초과|넘게|넘지|최대|함께|같이|동시에|공복|빈속|식전|식후""", "iu")
    val STOP_ZH = SafetyPattern("""停止|停用|停服|停药|停藥|不要(?:再)?(?:服用|吃|使用)|请勿服用|請勿服用|勿服用|禁止服用|不可服用""", "iu")
    val NOT_NOW_ZH = SafetyPattern("""(?:不要|不可|不能|不得|请勿|請勿|勿|别|別|切勿)\p{L}{0,24}?停|如果|如若|若|假如|一旦|如有|如出现|如出現|(?<![小暂暫同按及准準])[时時]|之前|以前|术前|術前|前一天|之后|之後|以后|以後|[天日周週月]后|[天日周週月]後|超过|超過|多于|多於|最多|空腹|同时|同時|一起|同服|饮酒|飲酒|酒精""", "iu")
    val STOP_AM = SafetyPattern("""ያቁሙ|አቁሙ|ያቋርጡ|አቋርጡ|አይውሰዱ|አትውሰድ|አትውሰጂ""", "iu")
    val NOT_NOW_AM = SafetyPattern("""አያቁሙ|አያቋርጡ|ማቆም\s*የለብዎትም|አታቁም|አታቋርጥ|እስከ|ከሆነ|ካለብዎት|ካለዎት|ካጋጠመዎት|ቢያጋጥምዎ|ቢሰማዎ|ከተሰማዎ|በፊት|በኋላ|በላይ|ጋር|በባዶ\s*ሆድ|አልኮል""", "iu")
    val BULLET_ANY = SafetyPattern("""^\s*(?:(?:[-*•‣–]|\d{1,2}[.)])\s+|・|\d{1,2}[、．])""", "u")

    val all: Map<String, SafetyPattern> = mapOf(
        "WARNING_WORDS" to WARNING_WORDS,
        "NOT_EMERGENCY" to NOT_EMERGENCY,
        "ER" to ER,
        "WHEN_RULE_0" to WHEN_RULE_0,
        "WHEN_RULE_1" to WHEN_RULE_1,
        "WHEN_RULE_2" to WHEN_RULE_2,
        "WHEN_RULE_3" to WHEN_RULE_3,
        "WHEN_RULE_4" to WHEN_RULE_4,
        "WHEN_RULE_5" to WHEN_RULE_5,
        "WHEN_RULE_6" to WHEN_RULE_6,
        "WHEN_RULE_7" to WHEN_RULE_7,
        "WHEN_RULE_8" to WHEN_RULE_8,
        "OTHER_LATIN" to OTHER_LATIN,
        "NEGATION" to NEGATION,
        "STOP" to STOP,
        "NOT_NOW" to NOT_NOW,
        "BULLET" to BULLET,
        "WARNING_MORE" to WARNING_MORE,
        "NOT_EMERGENCY_MORE" to NOT_EMERGENCY_MORE,
        "STOP_VI" to STOP_VI,
        "NOT_NOW_VI" to NOT_NOW_VI,
        "STOP_FR" to STOP_FR,
        "NOT_NOW_FR" to NOT_NOW_FR,
        "STOP_KO" to STOP_KO,
        "NOT_NOW_KO" to NOT_NOW_KO,
        "STOP_ZH" to STOP_ZH,
        "NOT_NOW_ZH" to NOT_NOW_ZH,
        "STOP_AM" to STOP_AM,
        "NOT_NOW_AM" to NOT_NOW_AM,
        "BULLET_ANY" to BULLET_ANY,
    )
}
