// Generated by mobile/shared/gen-native-patterns.py from mobile/shared/safety-vectors.json. Do not edit by hand.
package com.stephensookra.atlas.data

import java.util.regex.Pattern

/** One pattern from the website's safety rules: its exact source and JavaScript flags. */
data class SafetyPattern(val source: String, val flags: String) {
    /** Compiled with the website's meaning: "i" is case-insensitive (Unicode), \s is JavaScript's \s. */
    fun regex(): Regex = Pattern.compile(
        source.replace("""\s""", JS_SPACE_CLASS),
        if ('i' in flags) Pattern.CASE_INSENSITIVE or Pattern.UNICODE_CASE else 0,
    ).toRegex()

    companion object {
        /** JavaScript's \s, spelled out (Java's \s is ASCII only). */
        const val JS_SPACE_CLASS = """[\t\n\u000B\f\r \u00A0\u1680\u2000-\u200A\u2028\u2029\u202F\u205F\u3000\uFEFF]"""
    }
}

/** The patterns of web/src/lib/warningPin.ts and web/src/lib/stepsView.ts, word for word. */
@Suppress("ObjectPropertyName", "PropertyName")
object SafetyPatterns {
    val WARNING_WORDS = SafetyPattern("""(?<![\p{L}\p{N}])(?:911|emergency\s+(?:room|department|services|care)|emergencies|emergency|urgent\s+care|go\s+to\s+the\s+(?:nearest\s+)?hospital|seek\s+(?:\p{L}+\s+)?(?:care|help|attention|treatment)|get\s+(?:medical\s+)?help\s+(?:right\s+away|now|immediately)|call\s+(?:(?:the|your|our)\s+)?(?:\p{L}+['’]s\s+)?(?:office|clinic|doctor|physician|provider|nurse|care\s+team)\s+(?:right\s+away|immediately|at\s+once|now)|chest\s+(?:pain|pressure|tightness)|(?:trouble|difficulty|hard)\s+breathing|short(?:ness)?\s+of\s+breath|can(?:no|['’])t\s+breathe|cannot\s+breathe|faint(?:ing|ed)|feel(?:s|ing)?\s+faint|pass(?:ing)?\s+out|seizures?|stroke|sudden\s+(?:weakness|numbness|confusion)|severe\s+(?:bleeding|pain|headache|allergic)|suicid\p{L}*|llame\s+al\s+911|sala\s+de\s+emergencias?|emergencias?|urgencias|vaya\s+al\s+hospital|busque\s+(?:atenci[oó]n|ayuda)|dolor\s+(?:de|en\s+el)\s+pecho|dificultad\s+para\s+respirar|falta\s+de\s+aire|desmay\p{L}*|convulsi\p{L}*)(?![\p{L}\p{N}])""", "iu")
    val NOT_EMERGENCY = SafetyPattern("""(?<![\p{L}\p{N}])(?:not\s+(?:an\s+|a\s+)?|non-?|no\s+es\s+(?:una\s+)?)(?:emergency|emergencia|urgent)(?![\p{L}\p{N}])""", "giu")
    val ER = SafetyPattern("""(?<![\p{L}\p{N}])(?:ER)(?![\p{L}\p{N}])""", "u")

    val all: Map<String, SafetyPattern> = mapOf(
        "WARNING_WORDS" to WARNING_WORDS,
        "NOT_EMERGENCY" to NOT_EMERGENCY,
        "ER" to ER,
    )
}
